apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    env: sandbox
spec:
  type: NodePort
  ports:
   - protocol: TCP
     port: 92  # pod port = container port
     targetPort: 80  # service port
     nodePort: 30001 # external ip of the minikube node
  selector:
     env: sandbox
    # env: prod