# Use the official Node.js image as the base image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the container
COPY vue-app-server/package*.json ./

# Install app dependencies
RUN npm install

# Copy the application code to the container
COPY vue-app-server/ .

# Expose the port on which the app runs
EXPOSE 3000

# Command to run the application
CMD ["node", "app.js"]
