version: "3"

services:
  frontend:
    image: acrshubdemo01.azurecr.io/frontend-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    image: acrshubdemo01.azurecr.io/backend-image:latest
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "3000:3000"
